import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-media-buying-agency-fee-reconciliation",
  "engine": "recovery",
  "title": "Media Buying & Agency Fee Reconciliation",
  "shortTitle": "Media Spend Assurance",
  "tagline": "Reconcile planned, delivered, invoiced, rebated, and fee-bearing media spend",
  "industry": "Advertising Investment Governance",
  "uiPort": 4568,
  "apiPort": 5568,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Media investment reconciled to delivery, contract economics, and client entitlements",
  "valueNarrative": "Connect scopes of work, media plans, IOs, platform delivery, verification, invoices, fees, rebates, credits, and makegoods.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "verifiedAmount",
    "actualLabel": "Billed media and fees",
    "expectedLabel": "Verified contract amount",
    "varianceLabel": "Potential media recovery",
    "direction": "actual-minus-expected",
    "finding": "Plan, delivery, verification, fee, rebate, and invoice evidence indicate unsupported media spend.",
    "actions": [
      "Reconcile plan, insertion order, platform delivery, and invoice",
      "Validate rates, fees, technology charges, rebates, and credits",
      "Secure makegoods or financial adjustment",
      "Reconcile recovery and update buying controls"
    ]
  }
},[
feature("agency-and-scope-library","MSA01","Agency and scope library","Reconcile agency and scope library using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed agency and scope library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("campaign-and-media-plan-registry","MSA02","Campaign and media-plan registry","Reconcile campaign and media-plan registry using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed campaign and media-plan registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("insertion-order-ingestion","MSA03","Insertion-order ingestion","Reconcile insertion-order ingestion using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed insertion-order ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("platform-delivery-reconciliation","MSA04","Platform delivery reconciliation","Reconcile platform delivery reconciliation using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed platform delivery reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("rate-and-cpm-validation","MSA05","Rate and CPM validation","Reconcile rate and cpm validation using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed rate and cpm validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("underdelivery-detection","MSA06","Underdelivery detection","Reconcile underdelivery detection using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed underdelivery detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("invalid-traffic-and-viewability","MSA07","Invalid traffic and viewability","Reconcile invalid traffic and viewability using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed invalid traffic and viewability decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("agency-fee-recalculation","MSA08","Agency fee recalculation","Reconcile agency fee recalculation using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed agency fee recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("technology-fee-audit","MSA09","Technology fee audit","Reconcile technology fee audit using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed technology fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("rebate-and-incentive-reconciliation","MSA10","Rebate and incentive reconciliation","Reconcile rebate and incentive reconciliation using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed rebate and incentive reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("credit-and-makegood-control","MSA11","Credit and makegood control","Reconcile credit and makegood control using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed credit and makegood control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("invoice-exception-workbench","MSA12","Invoice exception workbench","Reconcile invoice exception workbench using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed invoice exception workbench decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("agency-platform-dispute","MSA13","Agency platform dispute","Reconcile agency platform dispute using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed agency platform dispute decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("payment-and-recovery-reconciliation","MSA14","Payment and recovery reconciliation","Reconcile payment and recovery reconciliation using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed payment and recovery reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]}),
feature("campaign-agency-and-channel-analytics","MSA15","Campaign agency and channel analytics","Reconcile campaign agency and channel analytics using agency agreements, media plans, insertion orders, platform delivery, third-party verification, invoices, fees, rebates, credits, and makegoods.","Produce a governed campaign agency and channel analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agencyPlatform","Agency / Platform","text","Northstar Media Group"],["campaignPeriod","Campaign / Period","text","CMP-8841 / 2026-Q2"],["billedAmount","Billed Media & Fees","currency",2840000],["verifiedAmount","Verified Contract Amount","currency",2515000]],{amountField:"billedAmount",subjects:["Programmatic campaign","Linear television buy","Paid social campaign","Search campaign","Out-of-home campaign"]})
]);
